tulius/games/urls.py
from django.conf.urls import patterns, url
from .views import *
from .game_edit_catalog import *
from .game_edit_views import *
from .requests_view import make_game_request, cancel_game_request, role_assign_user, role_clear_user

urlpatterns = patterns ('',
    # game list and details
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^announced/$', AnnouncedGames.as_view(), name='announced_games'),
    url(r'^accepting/$', RequestAcceptingGames.as_view(), name='request_accepting_games'),
    url(r'^awaiting_start/$', AwaitingStartGames.as_view(), name='awaiting_start_games'),
    url(r'^current/$', CurrentGames.as_view(), name='current_games'),
    url(r'^completed/$', CompletedOpenedGames.as_view(), name='completed_opened_games'),
    url(r'^add_game/(?P<pk>\d+)/$', CreateGame.as_view(), name='add_game'),
    url(r'^game/(?P<pk>\d+)/$', GameView.as_view(), name='game'),
    url(r'^delete_game/(?P<pk>\d+)/$', DeleteGame.as_view(), name='delete_game'),
    url(r'^change_story/(?P<pk>\d+)/$', ChangeGameStoryView.as_view(), name='change_game_story'),
    url(r'^view_role/(?P<pk>\d+)/$', GameRoleView.as_view(), name='view_role'),
    url(r'^edit_game/(?P<game_id>\d+)/main/$', GameAdminMain.as_view(), name=EDIT_GAME_PAGES_MAIN),
    url(r'^edit_game/(?P<game_id>\d+)/texts/$', GameAdminTexts.as_view(), name=EDIT_GAME_PAGES_TEXTS),
    url(r'^edit_game/(?P<game_id>\d+)/users/$', GameAdminUsers.as_view(), name=EDIT_GAME_PAGES_USERS),
    url(r'^edit_game/(?P<game_id>\d+)/graphics/$', GameAdminGraphics.as_view(), name=EDIT_GAME_PAGES_GRAPHICS),
    url(r'^edit_game/(?P<game_id>\d+)/roles/$', GameEditRoles.as_view(), name=EDIT_GAME_PAGES_ROLES),
    url(r'^edit_game/(?P<pk>\d+)/illustrations/$', GameEditIllustrationsView.as_view(), name=EDIT_GAME_PAGES_ILLUSTRATIONS),
    url(r'^edit_game/(?P<pk>\d+)/materials/$', GameEditMaterialsView.as_view(), name=EDIT_GAME_PAGES_MATERIALS),
    url(r'^edit_game/(?P<pk>\d+)/request_form/$', EditRequestView.as_view(), name=EDIT_GAME_PAGES_REQUEST_FORM),
    url(r'^edit_game/(?P<pk>\d+)/requests/$', EditRequestsView.as_view(), name=EDIT_GAME_PAGES_REQUESTS),
    url(r'^edit_game/(?P<pk>\d+)/winners/$', EditWinnersView.as_view(), name=EDIT_GAME_PAGES_WINNERS),
    url(r'^edit_game/(?P<pk>\d+)/forum/$', GameForumView.as_view(), name=EDIT_GAME_PAGES_FORUM),
    url(r'^edit_game/(?P<game_id>\d+)/players/$', game_edit_players, name='game_edit_players'),
        
    url(r'^edit_game/(?P<pk>\d+)/add_role/$', AddRoleView.as_view(), name='add_role'),
    url(r'^edit_game/(?P<pk>\d+)/add_material/$', AddMaterialView.as_view(), name='add_material'),
    url(r'^role/(?P<pk>\d+)/$', GameEditRoleView.as_view(), name='role'),
    url(r'^role/(?P<pk>\d+)/text/$', GameRoleTextView.as_view(), name='role_text'),
    url(r'^role/(?P<pk>\d+)/assign/$', EditRoleAssignView.as_view(), name='role_assign'),
    url(r'^edit_illustration/(?P<pk>\d+)/$', EditIllustrationView.as_view(), name='edit_illustration'),
    url(r'^edit_illustration/(?P<pk>\d+)/delete/$', DeleteIllustration.as_view(), name='illustration_delete'),
    url(r'^edit_material/(?P<pk>\d+)/$', EditMaterialView.as_view(), name='edit_material'),
    url(r'^edit_material/(?P<pk>\d+)/delete/$', DeleteMaterial.as_view(), name='material_delete'),
    url(r'^material/(?P<pk>\d+)/$', MaterialView.as_view(), name='material'),
    
    url(r'^game_request/(?P<game_id>\d+)/$', make_game_request, name='game_request'),
    url(r'^game_invite/(?P<game_id>\d+)/$', invite_player, name='game_invite'),
    url(r'^cancel_request/(?P<game_id>\d+)/$', cancel_game_request, name='cancel_game_request'),
    url(r'^role/(?P<role_id>\d+)/assign(?P<user_id>\d+)/$', role_assign_user, name='role_assign_user'),
    url(r'^role/(?P<role_id>\d+)/assign(?P<user_id>\d+)/roles/$', role_assign_user, {'backtoroles': True}, name='role_assign_user_roles'),
    url(r'^role/(?P<role_id>\d+)/clearuser/$', role_clear_user, name='role_clear_user'),
)

tulius/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.sitemaps import views as sitemaps_views
from django.contrib import admin
from tulius.views import HomeView, StatisticsView
from django.conf import settings
from tulius import forum, gameforum
from djfw.flatpages.views import FlatpagesList
from .sitemap import sitemaps
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^sitemap.xml$', sitemaps_views.index, {'sitemaps': sitemaps, 'sitemap_url_name': 'sitemaps'}),
    url(r'^sitemap-(?P<section>.+)\.xml$', sitemaps_views.sitemap, {'sitemaps': sitemaps}, name='sitemaps'),
    
    url(r'^accounts/', include('djfw.accounts.urls')),
    url(r'^tinymce/', include('djfw.tinymce.urls',  namespace='tinymce')),
    url(r'^wysibb/', include('djfw.wysibb.urls',  namespace='wysibb')),
    url(r'^news/', include('djfw.news.urls',  namespace='news')),
    url(r'^flatpages/$', FlatpagesList.as_view(),  name='flatpages'),
    url(r'^autocomplete/', include('djfw.autocomplete.urls',  namespace='autocomplete')),
    url(r'^bugtracker/', include('djfw.bugtracker.urls',  namespace='bugtracker')),
    url(r'^profiler/', include('djfw.profiler.urls',  namespace='profiler')),
    url(r'^installer/', include('djfw.installer.urls', namespace='installer')),
    
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^statistics/$', StatisticsView.as_view(), name='stats'),

    url(r'^players/', include('tulius.players.urls', namespace='players')),
    url(r'^games/', include('tulius.games.urls',  namespace='games')),
    url(r'^forums/', include(forum.site.urls)),
    url(r'^stories/', include('tulius.stories.urls',  namespace='stories')),
    url(r'^play/', include(gameforum.site.urls)),
    
    url(r'^bugs/', include('tulius.bugs.urls',  namespace='bugs')),
    url(r'^vk/', include('tulius.vk.urls',  namespace='vk')),
    url(r'^counters/', include('tulius.counters.urls',  namespace='counters')),
)

handler404 = 'tulius.views.error404'
handler500 = 'tulius.views.error500'

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
             {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )
    urlpatterns += patterns('django.contrib.staticfiles.views',
        url(r'^static/(?P<path>.*)$', 'serve'),
    )

from djfw.installer.signals import maintaince_finished, maintaince_started
from tulius.bugs.views import maint_updated
        

def set_locale(sender, **kwargs):
    import platform
    is_windows = platform.system() == 'Windows'
    if not is_windows:
        import locale
        locale.setlocale(locale.LC_ALL, 'ru_RU.UTF-8')

maintaince_finished.connect(maint_updated)
maintaince_started.connect(set_locale)

set_locale(None)

tulius/templates/snippets/advanced_editor.html
{% include "tinymce/init_editor.html" %}
{% load url from future %}

<script type="text/javascript">
    tinyMCE.init({
        base_dj_url: "{% url 'tinymce:index' %}",
        mode : "textareas",
        theme: 'advanced',
        plugins : "table, emotions, file_upload",
        theme_advanced_toolbar_location: 'top',
        theme_advanced_toolbar_align: 'left',
        theme_advanced_buttons1 : 
            "formatselect, separator, "+
            "bold, italic, underline, strikethrough, separator," +
            "bullist, numlist, separator, outdent, indent, separator, undo, redo, separator," +
            "link, unlink, image, blockquote, separator, removeformat, separator, " +
            "forecolor, backcolor",
        theme_advanced_buttons2 : "sub, sup, separator, code, separator, tablecontrols, separator, emotions, file_upload",
        theme_advanced_buttons3 : "",
        theme_advanced_blockformats : "p,h1,h2,h3,h4,h5,h6,",
        height : "520",
        width : "100%"
    });
</script>

tulius/templates/snippets/simple_editor.html
{% include "tinymce/init_editor.html" %}
{% load url from future %}

<script type="text/javascript">
    tinyMCE.init({
        base_dj_url: "{% url 'tinymce:index' %}",
        mode : "textareas",
        language : 'ru',
        theme: 'advanced',
        plugins : "emotions,bbcode, file_upload",
        theme_advanced_toolbar_location: 'top',
        theme_advanced_toolbar_align: 'left',
        theme_advanced_buttons1 : "fontsizeselect,bold,italic,underline,strikethrough, separator," +
            "undo,redo,link,unlink,image,forecolor," +
            "removeformat,cleanup,emotions, file_upload, blockquote, separator, code",
        theme_advanced_buttons2 : "",
        theme_advanced_buttons3 : "",
        theme_advanced_blockformats : "p,h1,h2,h3,h4,h5,h6,",
        theme_advanced_path : false,
        theme_advanced_statusbar_location : "none",
        content_css : "/media/css/tinymce-forum.css",
        preformatted : true,
        forced_root_block : '',
        force_br_newlines : false,
        force_p_newlines : false,
        width : "100%"
    });
</script>